# run on terminal 
 ## docker compose up -d, download and install pgAdmin4 from pgadmin.org
services:
  postgres:
    image: postgres:17
    container_name: pgsql_contaner_for_mybdgt_panner_db
    restart: always
    environment:
      POSTGRES_USER: pgsql_user
      POSTGRES_PASSWORD: myC0mplexPwd
      POSTGRES_DB: postgres
    ports:
      - "3006:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
