version: '3.9'
services:
  # asp.net web application
  webapp:
    container_name: budgetplanner-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
